# Settings that apply to all modules
[global]
# How long notifications should stay up (in seconds)
notification_timeout = 10

# OpenWeatherMap configuration
[openweathermap]
# Enable / disable OpenWeatherMap integration
enabled = false

# Register at https://openweathermap.org to get your API key
# If you don't want to write your key here, you can delete this line and use the OWM_API_KEY environment variable instead
api_key = "YOUR_API_KEY"

# This is for Montreal, find your city at https://openweathermap.org
# The id will be the last part of the URL
city_id = "6077243"

# When notifications are sent, the notification title comes from OpenWeatherMap
# You can customize the message body, or use "" to leave it blank
notification_body = "Expected within the next 3 hours"

# How often should we fetch weather data (in seconds)
sync_frequency = 1800 # 30 minutes

# Output format, using Handlebars syntax, meaning variables should be used like {{ this }}
# Available tokens are:
# - temp_celcius
# - temp_kelvin
# - temp_fahrenheit
# - temp_icon
# - trend
# - forecast_celcius
# - forecast_kelvin
# - forecast_fahrenheit
# - forecast_icon
display = "{{ temp_icon }} {{ temp_celcius }}°C {{ trend }} {{ forecast_icon }} {{ forecast_celcius }}°C"

# MPD configuration
[mpd]
# Enable / disable mpd integration
enabled = false

# Top level directory containing your MPD collection
# Should be the same value as "music_directory" from your mpd.conf
music_directory = "/mnt/media/music"

# Cover art files should have standardized names and formats within your collection
# Specify the file name we should look for here
cover_name = "cover.jpg"

# When this is enabled, songs with missing cover image will not trigger a notification
skip_missing_cover = false

# Twitch configuration
[twitch]
# Enable / disable Twitch integration
enabled = false
# Twitch client id for ntfd, you probably don't want to change that
client_id = "3szce2tmzmjbvug7x3fkiwhe5xgk3f"
